permalink: /:year/:title

collections:
  archives:
    output: true
  page:
    output: true

_options:
  content:
    styles: /assets/editor.css
  text_html:
    format: h1 h2 h3 p a img
    styles: /assets/editor.css
    bold: true
    numberedlist: true
    right: right
    center: centered
    left: left
    link: true
    image: true
  col-1_html:
    format: h1 h2 h3 p a img
    styles: /assets/editor.css
    bold: true
    numberedlist: true
    right: right
    center: centered
    left: left
    link: true
    image: true
  col-2_html:
    format: h1 h2 h3 p a img
    styles: /assets/editor.css
    bold: true
    numberedlist: true
    right: right
    center: centered
    left: left
    link: true
    image: true
  col-3_html:
    format: h1 h2 h3 p a img
    styles: /assets/editor.css
    bold: true
    numberedlist: true
    right: right
    center: centered
    left: left
    link: true
    image: true
  pre_img_text_html:
    format: h2 h3 p a img
    link: true
    styles: /assets/editor.css
    bold: true
    numberedlist: true
    right: right
    center: center
  post_img_text_html:
    format: h2 h3 p a
    link: true
    styles: /assets/editor.css
    bold: true
    numberedlist: true
    right: right
    center: center


page_blocks: []
_array_structures:
  page_blocks:
    - label: banner section
      icon: video
      value:
        _id: back_video
        text_html:
        bg-class:
        img_path:
        img_description:
        overlay_rgba:
        text_rgba:
        buy_button:
    - label: Vimeo section
      icon: video
      value:
        _id: vimeo
        heading:
        sub_heading:
        bg-class:
        vimeo_id:
        text_html:
        buy_button_text: enroll now
        button:
        - class:
          link_url:
          text:
          id:
    - label: Module section
      icon: video
      value:
        _id: modual_demo
        heading:
        sub_heading:
        bg-class:
        vimeo_id:
        text_html:
    - label: Icon section
      icon: video
      value:
        _id: icon_section
        heading:
        bg-class:
        sub_heading:
        text_html:
        icon_block:
        - img_path:
          img_alt:
          heading:
          text_html:
    - label: Large image section
      icon: img
      text:
      value:
        _id: gif
        heading:
        bg-class:
        pre_img_text_html:
        img_path:
        img_alt:
        post_img_text_html:
    - label: Chris Lau section
      icon: img
      text:
      value:
        _id: Chris_Lau
        heading:
        bg-class:
        pre_img_text_html:
        headshot_path:
        headshot_alt:
        img_path:
        img_alt:
        post_img_text_html:
    - label: map section
      icon: img
      text:
      value:
        _id: map
        heading:
        bg-class:
        pre_img_text_html:
        map_path:
        map_alt:
        img_path:
        img_alt:
        post_img_text_html:
    - label: Reveiw section
      icon: video
      value:
        _id: review
        text_html:
        bg-class:
        img_path:
        overlay_rgba:
        vimeo_id:
        next_section_heading:
    - label: Text Block
      icon: ballot
      value:
        bg-class:
        _id: text-block
        text_html:
        buy_button: false
    - label: Image and text grid
      icon: ballot
      value:
        _id: image-text-grid
        bg-class:
        first-pic-flip: false
        has_links: false
        layer:
          - image_path:
            img-fill: true
            sub_heading:
            heading:
            text_html:
    - label: Acordian Section
      icon: ballot
      value:
        _id: faq
        heading:
        bg-class:
        text:
        has_links: false
        dropdown:
          - heading:
            list_item:
              - text_html:
    - label: Partners Section
      icon: ballot
      value:
        _id: partners
        heading:
        bg-class:
        img_path:
        overlay_rgba:
        text_rgba:
        logo:
          - image_path:
            alt:
            opacity:
    - label: Three Columns
      icon: ballot
      value:
        _id: columns-3
        heading_html:
        bg-class:
        col-1_html:
        col-2_html:
        col-3_html:
    - label: Mixed Columns
      icon: ballot
      value:
        _id: columns-mixed
        bg-class:
        col-1_html:
        col-2_html:
        col-3_html:
    - label: banner 2 coloumn section
      icon: img
      value:
        _id: banner-two-col
        text_html:
        bg-class:
        img_path:
        img_description:
        overlay_rgba:
        text_rgba:
        buy_button:
        col_2_image_path:
        col_2_image_description:

    - label: banner-video-section
      icon: video
      value:
        _id: banner-video
        text_html:
        bg-class:
        bg-img_path:
        bg_video_path:
        overlay_rgba:
        text_rgba:
    - label: slider section
      icon: ballot
      value:
        bg-class:
        _id: text-block
        text_html:
        img_pre_filter_path:
        img_pre_filter_alt:
        img_post_filter_path:
        img_pre_filter_alt:
